package errors

const ALREADY_EXISTS = "ALREADY_EXISTS"
const INTERNAL = "INTERNAL"
const INVALID_ARGUMENT = "INVALID_ARGUMENT"
const NOT_FOUND = "NOT_FOUND"
const PERMISSION_DENIED = "PERMISSION_DENIED"
const UNAUTHENTICATED = "UNAUTHENTICATED"
